### ISSUE TITLE
网页端不可观看直播的直播间可以连接吗？

### ISSUE THREAD

**Issue by zhangyuxin123** [wushuaihua520/BarrageGrab#3]
项目主，您好！
    网页端提示如下：
![QQ截图20240609002231](https://github.com/wushuaihua520/BarrageGrab/assets/23115864/2244ca4c-12c2-45c4-abed-fdfcbeaf9b1b)

这个您这个可以连接吗？

**Comment by wushuaihua520** [comment]
你好，这种直播间也是可以连接的，不过得改一下
